### PR TITLE
Automatically determine when finalizers can be omitted

### PR DESCRIPTION
**Pull request by jacob-hughes**
This PR introduces support for optimising away finalizers for Vecs whose element
types can be statically determined not to need dropping.

This requires the user to specify `Boehm` as the global allocator in their
crate, and the -Zgc-destination-propagation flag must be enabled.

Right now, this won't work recursively. In other words, if one were to create a
value with the following type:

    Gc<Vec<Vec<usize>>

A finalizer would still be registered unnecessarily.

This is because the MIR pass which determines which Vecs are allocated directly
in GC space currently looks only at the top-level element type inside a Vec.

    Gc<Vec<Vec<usize>>
        ^   ^
        |   |
        |   +---- No Finalizer
        +----- Finalizer

In order for both finalizers to be removed, one must implement
`ManageableContents` for `Vec<usize>`.

### CODE REVIEW

**Comment by ltratt** [comment]
To the extent I understand this, it looks good. I would appreciate a quick glance from @vext01 because he understands rustc's internals better than I do.

**Comment by vext01** [comment]
What is ` -Zgc-destination-propagation` for?

**Comment by vext01** [comment]
> the MIR pass which determines which Vecs are allocated directly
in GC space currently looks only at the top-level element type inside a Vec.

So wouldn't it be the outer `Vec` which doesn't get a finaliser?

**Comment by jacob-hughes** [comment]
> What is ` -Zgc-destination-propagation` for?

This gates most of this work behind a debug flag. The reason is that this propagation stuff is predicated on the `BoehmAllocator` being defined as the global allocator by the user. 

It's not possible to make the `BoehmAllocator` the default in our rustc fork because it's not thread-safe, which would mean that we would get UB when bootstrapping.

**Comment by ltratt** [comment]
Given that we're going to have to specify the `-Z` flag fairly often, I do wonder if we can come up with something a little bit snappier than `gc-destination-propagation`?

**Comment by jacob-hughes** [comment]
> > the MIR pass which determines which Vecs are allocated directly
> > in GC space currently looks only at the top-level element type inside a Vec.
> 
> So wouldn't it be the outer `Vec` which doesn't get a finaliser?

I'm sorry, revisiting that diagram I see that it causes more confusion than it helps. What I was trying to say is that a finalizer is registered for the outer `Vec`, because the MIR pass can't yet work out whether its element type -- the inner `Vec<usize>` -- will need dropping (since it needs to look through more than one level of indirection).

**Comment by jacob-hughes** [comment]
> Given that we're going to have to specify the `-Z` flag fairly often, I do wonder if we can come up with something a little bit snappier than `gc-destination-propagation`?

It's a bit of a mouthful, but it's the most "accurate" name I think I've used for anything in this entire project yet!

**Comment by ltratt** [comment]
> It's a bit of a mouthful, but it's the most "accurate" name I think I've used for anything in this entire project yet!

OK.

I think we're ready to merge.

bors r+

**Comment by jacob-hughes** [comment]
@ltratt We could abbreviate it to `gcdp` and keep the long name in the description?

**Comment by ltratt** [comment]
We can fiddle with the name later if it turns out to be a real pain.

**Pull request merged**
